/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bhochhi' at '4/23/18 11:57 PM' with Gradle 2.10
 *
 * @author bhochhi, @date 4/23/18 11:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
